export enum ApiEndpoints {
    SURVEY_CONFIGURATION = `survey/{0}/{1}/configuration`,
    REGISTRATION_CONFIGURATION = `userRegistration/configuration/{0}`,
    ORGANIZATION_STUDY_SITES = `study/organization/{0}`,
    SURVEY_RESPONSES = `subject/{0}/surveyResponses`,
    UPDATE_SURVEY_STATUS = `survey/response/{0}/completionStatus`,
    SUBMIT_QUESTION_RESPONSE = `survey/{0}/response/section/{1}`,
    REGISTRATION_SUBMIT = `subject`,
    FETCH_SECTION_RESPONSES = `survey/response/section/{0}`,
    FETCH_LEGAL_STATEMENT = `person/{0}/{1}/legalAgreement`,
    UPDATE_LEGAL_STATEMENT = `person/{0}/legalAgreement`,
    UPDATE_SECTION_STATUS = `survey/response/section/{0}/completionStatus`,
    GET_SUBJECT_PROFILE_DETAILS = `subject/profile/{0}`,
    FETCH_ACCESS_TOKEN_FROM_REFRESH_TOKEN = `userAccount/refreshToken/{0}`,
    GET_LOGGED_IN_USER_DETAILS = `userAccount`,
    AUTHENTICATE_USER = `userAccount/authenticate`,
    GET_SIGNATURE_DETAILS = `signature/signatureDetails`,
    UPLOAD_SURVEY_DATA = `survey/upload/section/{0}`,
    FETCH_PASSWORD_ENCRYPTION_KEY = `userAccount/encryptionKey`,
    UPDATE_SUBJECT_LANGUAGE = `subject/{0}/person/{1}/{2}`
}